spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: chirp@sandbox728abce8f3bb48888ab0de3d9bd938e7.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp:
  rate-limit:
    ip:
      apply-limit: false