spring:
  application:
    name: chirp

  data:
    redis:
      host: "redis-16814.c243.eu-west-1-3.ec2.cloud.redislabs.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 16814
      connect-timeout: 5000ms
      timeout: 2000ms
  datasource:
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres
    username: postgres.iwapuwtlfkrevxqxnmkz
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  rabbitmq:
    host: "collie.lmq.cloudamqp.com"
    password: ${RABBITMQ_PASSWORD}
    username: fekmmqln
    ssl:
      enabled: true
    virtual-host: fekmmqln
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
          max-attempts: 3
          multiplier: 2

jwt:
  secret: ${JWT_SECRET_BASE64}
  expiration-minutes: 15

chirp:
  email:
    verification:
      expiry-hours: 24
    reset-password:
      expiry-minutes: 30

nginx:
  require-proxy: true
  trusted-ips:
    - "127.0.0.1" # nginx running on the same server
    - "::1" # nginx running on the same server (IPv6)
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate server)