spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: chirp@sandbox728abce8f3bb48888ab0de3d9bd938e7.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  email:
    url: "https://chirp.joaograca.com"
  rate-limit:
    ip:
      apply-limit: false